### PR TITLE
GH-1773 Fix potential duplicate runs

### LINKED ISSUE #1773: Double clicks can start duplicate runs
Clicking too fast when starting a run can cause multiple runs to be started.

_Issue created from a [Mattermost message](https://community.mattermost.com/_redirect/pl/xxno8tska7fuf8as7fniud1sya) *by @m-ripper*._

### PR DESCRIPTION
**Pull request by m-ripper**
## Summary

When the internet of the user or the server is slow, it is possible to start multiple runs at once by clicking the "Start run" button multiple times. The "Start run" button is now disabled while the client is waiting for the response from the server.

[Screencast from 01.02.2023 16:06:50.webm](https://user-images.githubusercontent.com/8669935/216080548-7966b752-3c38-49b2-ae8d-b2c19d471e47.webm)

## Ticket Link

Fixes #1773 

## Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

### CODE REVIEW

File: webapp/src/components/modals/run_playbook_modal.tsx [hunk 1]
```diff
@@ -138,7 +140,7 @@ const RunPlaybookModal = ({
                 onRunCreated(newPlaybookRun.id, newPlaybookRun.channel_id, statsData);
             }).catch(() => {
             // show error
-            });
+            }).finally(() => setIsSubmitting(false));
```
Comment (trilopin) [inline webapp/src/components/modals/run_playbook_modal.tsx:143]: wouldn't this be the case for using debounce?

Comment (m-ripper) [reply webapp/src/components/modals/run_playbook_modal.tsx:143]: Debounce could work as well, but would be more complicated to implement for no gain in usage, because the time frame would need to be hard-coded and cancel/flush would have to be used. This has the same result but is a lot simpler, what do you think?

**Review by trilopin — APPROVED** [review]
